# Generated by Django 4.2.30 on 2026-06-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(db_index=True, max_length=100, unique=True)),
                ('frecuencia', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Vocabulario',
                'verbose_name_plural': 'Vocabulario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('nombre_propio', 'Nombre propio'), ('unidad', 'Unidad'), ('particula', 'Partícula'), ('adjetivo', 'Adjetivo')], default='sustantivo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vocabulario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='juego.vocabulario')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['vocabulario_id'],
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('texto', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='juego.target')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
                'ordering': ['orden'],
                'unique_together': {('target', 'orden')},
            },
        ),
    ]
