# Generated by Django 4.2.30 on 2026-06-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('similitud', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ranking de palabra',
                'verbose_name_plural': 'Rankings de palabras',
            },
        ),
        migrations.AddField(
            model_name='target',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['activo', 'disponible'], name='idx_target_activo_disponible'),
        ),
        migrations.AddField(
            model_name='rankingpalabra',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='juego.target'),
        ),
        migrations.AddField(
            model_name='rankingpalabra',
            name='vocabulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='juego.vocabulario'),
        ),
        migrations.AddIndex(
            model_name='rankingpalabra',
            index=models.Index(fields=['target', 'rank'], name='juego_ranki_target__a380d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingpalabra',
            constraint=models.UniqueConstraint(fields=('target', 'vocabulario'), name='uq_ranking_target_vocab'),
        ),
        migrations.AddConstraint(
            model_name='rankingpalabra',
            constraint=models.UniqueConstraint(fields=('target', 'rank'), name='uq_ranking_target_rank'),
        ),
    ]
