# Generated by Django 4.2.30 on 2026-06-17 18:29

import unicodedata

from django.db import migrations, models


def normalizar(texto):
    nfkd = unicodedata.normalize("NFD", texto.lower())
    return "".join(c for c in nfkd if not unicodedata.combining(c))


def backfill_palabra_normalizada(apps, schema_editor):
    Vocabulario = apps.get_model("juego", "Vocabulario")
    filas = list(Vocabulario.objects.all())
    for v in filas:
        v.palabra_normalizada = normalizar(v.palabra)
    Vocabulario.objects.bulk_update(filas, ["palabra_normalizada"], batch_size=2000)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_rankingpalabra_target_disponible_target_generado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulario',
            name='palabra_normalizada',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.RunPython(backfill_palabra_normalizada, noop),
    ]
